# Generated by Django 3.1.7 on 2021-04-01 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selectfields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_factor', models.CharField(default='', max_length=50)),
                ('probability_rating', models.CharField(default='', max_length=50)),
                ('economic_aspects_consequence_factor', models.CharField(default='', max_length=50)),
                ('economic_aspects_consequence_rating', models.CharField(default='', max_length=50)),
                ('health_and_safety_aspects_consequence_factor', models.CharField(default='', max_length=50)),
                ('health_and_safety_aspects_consequence_rating', models.CharField(default='', max_length=50)),
                ('environmental_aspects_consequence_factor', models.CharField(default='', max_length=50)),
                ('environmental_aspects_consequence_rating', models.CharField(default='', max_length=50)),
                ('overall_consequence_factor', models.CharField(default='', max_length=50)),
                ('overall_consequence_rating', models.CharField(default='', max_length=50)),
                ('risk_rating', models.CharField(default='', max_length=50)),
                ('corrosion_rate', models.CharField(default='', max_length=50)),
                ('acceleration_factor_for_pitting', models.CharField(default='', max_length=50)),
                ('adjusted_corrosion_rate', models.CharField(default='', max_length=50)),
                ('remaining_life', models.CharField(default='', max_length=50)),
                ('confidence_factor', models.CharField(default='', max_length=50)),
                ('confidence_factor_adjustement', models.CharField(default='', max_length=50)),
                ('ajusted_confidence_factor', models.CharField(default='', max_length=50)),
                ('interval_before_next_required_inspection', models.CharField(default='', max_length=50)),
                ('next_inspection', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Results',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='ProbabilityFactorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_plates_external_coatin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.bottomplatesexternalcoating')),
                ('bottom_plates_internal_coating_or_linin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.bottomplatesinternalcoatinglining')),
                ('effectiveness_of_drainages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.effectivenessofdrainage')),
                ('foundation_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.foundationtype')),
                ('heating_coils_in_tanks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.heatingcoilsintank')),
                ('heights_of_foundation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.heightoffoundation')),
                ('impresses_cathodic_protect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.impresscathodicprotection')),
                ('products_corrosivity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.productcorrosivity')),
                ('sacrificial_cathodic_propect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.sacrificialcathodicpropection')),
                ('storage_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.storageconditions')),
                ('types_of_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.typeofbottom')),
            ],
            options={
                'verbose_name': 'Probability Factor Data',
                'verbose_name_plural': 'Probability Factor Data',
            },
        ),
        migrations.CreateModel(
            name='InspectionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inspection', models.DateField(default=django.utils.timezone.now)),
                ('minimum_thickness_measured_during_previous_inspection', models.CharField(default='5', max_length=100, verbose_name='20a: Minimum thickness measured during previous inspection')),
                ('period_of_service_between_previous_inspection_and_this_inspection', models.CharField(default='10', max_length=100, verbose_name='20b: Period of service between previous inspection and this inspection')),
                ('minimum_thickness_measured_during_present_inspection', models.CharField(default='5', max_length=100, verbose_name='21a: Minimum thickness measured during present inspection')),
                ('minimum_allowable_bottom_place_thickness', models.CharField(default='4', max_length=100, verbose_name='21b: Minimum allowable bottom place thickness')),
                ('NDT_method_used_for_thickness_measurements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.ndtmethodusedforthicknessmeasurements')),
                ('acceleration_factor_for_pitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.accelerationfactorforpitting')),
                ('frequency_of_internal_inspections_performed_during_service_life', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.frequencyofinternalinspections')),
                ('type_of_interconnecting_bottom_plate_welds_outside_of_annular_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.typeofinterconnectingbottomplatewelds')),
            ],
            options={
                'verbose_name': 'Inspection Data',
                'verbose_name_plural': 'Inspection Data',
            },
        ),
        migrations.CreateModel(
            name='ConsequenceFactorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.costofrepair')),
                ('environmetal_hazard_to_soil_and_water_as_the_potential_to_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.environmetalhazardtosoilandwater')),
                ('likelihood_of_injury_to_personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.likelihoodofinjurytopersonnel')),
                ('location_of_tank_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.locationoftankfarm')),
                ('probable_magnitude_of_product_loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.probablemagnitudeofproductloss')),
                ('product_flammability_as_per_MCSP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.productflammabilityaspermcsp')),
                ('product_toxicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.producttoxicity')),
                ('time_to_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.timetorepair')),
                ('vapour_emission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.vapouremission')),
            ],
            options={
                'verbose_name': 'Consequence Factor Data',
                'verbose_name_plural': 'Consequence Factor Data',
            },
        ),
        migrations.CreateModel(
            name='AllModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence_factor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottom_plates.consequencefactordata')),
                ('inspection_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottom_plates.inspectiondata')),
                ('probability_factor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottom_plates.probabilityfactordata')),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottom_plates.results')),
            ],
        ),
    ]
