# Generated by Django 3.2 on 2021-05-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0041_istheconstructionsuchthatcorrosionmaybereducedbythechosenweldconfiguration'),
        ('bottom_plates', '0004_consequencefactordata_time_to_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondata',
            name='type_of_interconnecting_bottom_plate_welds_outside_of_annular_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selectfields.istheconstructionsuchthatcorrosionmaybereducedbythechosenweldconfiguration'),
        ),
    ]
