# Generated by Django 3.2 on 2021-05-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottom_plates', '0005_alter_inspectiondata_type_of_interconnecting_bottom_plate_welds_outside_of_annular_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectiondata',
            old_name='type_of_interconnecting_bottom_plate_welds_outside_of_annular_section',
            new_name='Is_the_Construction_such_that_Corrosion_may_be_Reduced_by_the_Chosen_Weld_Configuration',
        ),
    ]
