# Generated by Django 3.1.7 on 2021-04-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bottom_plates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('default_values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bottom_plates.allmodels')),
            ],
        ),
    ]
