# Generated by Django 3.2 on 2021-05-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0002_auto_20210509_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areproceduresinplacetopreventwatercontact',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No - Score=0')], default='Yes - Score=1', max_length=350, verbose_name='Are Procedures In Place To Prevent Water Contact'),
        ),
        migrations.AlterField(
            model_name='isthecorrosionratedeterminedwithatleast2sources',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No - Score=0')], default='Yes - Score=1', max_length=350, verbose_name='Is The Corrosion Rate Determined With At Least 2 Sources'),
        ),
        migrations.AlterField(
            model_name='isthedegradationspeedcalculatedbyusingatleast3measurementpoints',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No - Score=0')], default='Yes - Score=1', max_length=350, verbose_name='Is The Degradation Speed Calculated By Using At Least 3 Measurement Points'),
        ),
    ]
