# Generated by Django 3.2 on 2021-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0004_auto_20210509_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areproceduresinplacetopreventwatercontact',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='Yes - Score=1', max_length=350),
        ),
        migrations.AlterField(
            model_name='isthecorrosionratedeterminedwithatleast2sources',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='Yes - Score=1', max_length=350),
        ),
        migrations.AlterField(
            model_name='isthedegradationspeedcalculatedbyusingatleast3measurementpoints',
            name='name',
            field=models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='Yes - Score=1', max_length=350),
        ),
        migrations.AlterField(
            model_name='whichmethodisused',
            name='name',
            field=models.CharField(choices=[('LS fit - Score=0.6', 'LS fit'), ('Last 2 Points - Score=0.5', 'Last 2 Points'), ('Literature - Score=0', 'Literature'), ('Similar Service - Score=1', 'Similar Service'), ('2 Methods Used - Score=1', '2 Methods Used')], default='Yes - Score=1', max_length=350),
        ),
    ]
