# Generated by Django 3.2 on 2021-05-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0005_auto_20210509_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whichmethodisused',
            options={'verbose_name': 'Which Method Is Used', 'verbose_name_plural': 'Which Method Is Used'},
        ),
    ]
