# Generated by Django 3.2 on 2021-05-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0006_alter_whichmethodisused_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areproceduresinplacetopreventwatercontact',
            options={'verbose_name': 'Are Procedures In Place To Prevent Water Contact', 'verbose_name_plural': 'Are Procedures In Place To Prevent Water Contact'},
        ),
        migrations.AlterModelOptions(
            name='isthecorrosionratedeterminedwithatleast2sources',
            options={'verbose_name': 'Is The Corrosion Rate Determined With At Least 2 Sources', 'verbose_name_plural': 'Is The Corrosion Rate Determined With At Least 2 Sources'},
        ),
        migrations.AlterModelOptions(
            name='isthedegradationspeedcalculatedbyusingatleast3measurementpoints',
            options={'verbose_name': 'Is The Degradation Speed Calculated By Using At Least 3 Measurement Points', 'verbose_name_plural': 'Is The Degradation Speed Calculated By Using At Least 3 Measurement Points'},
        ),
    ]
