# Generated by Django 3.2 on 2021-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0007_auto_20210509_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresscathodicprotection',
            name='name',
            field=models.CharField(choices=[('All readings around the periphery > 0.85 V - Score=0', 'All readings around the periphery > 0.85 V'), ('0.6 V < All readings around the periphery < 0.85 V - Score=1', '0.6 V < All readings around the periphery < 0.85 V'), ("All readings around periphery < 0.6 V or CP doesn't exist - Score=2", "All readings around periphery < 0.6 V or CP doesn't exist")], default='All readings around the periphery > 0.85 V - Score=0', max_length=100, verbose_name='1: Impressed cathodic protection'),
        ),
    ]
