# Generated by Django 3.2 on 2021-05-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0008_alter_impresscathodicprotection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impresscathodicprotection',
            options={'verbose_name': 'Impressed cathodic protection', 'verbose_name_plural': 'Impressed cathodic protection'},
        ),
    ]
