# Generated by Django 3.2 on 2021-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0011_alter_sacrificialcathodicpropection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomplatesinternalcoatinglining',
            name='name',
            field=models.CharField(choices=[('Internal coating applied and quality is sound - Score=0', 'Internal coating applied and quality is sound'), ('Internal coating applied but quality is poor - Score=1', 'Internal coating applied but quality is poor'), ('No coating is applied - Score=2', 'No coating is applied')], default='Internal coating applied and quality is sound - Score=0', max_length=100, verbose_name='3: Bottom plates internal coating or lining'),
        ),
    ]
