# Generated by Django 3.2 on 2021-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0013_alter_bottomplatesexternalcoating_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageconditions',
            name='name',
            field=models.CharField(choices=[('Temperature of product < 40°C - Score=0', 'Temperature of product < 40°C'), ('Temperature of product between 40°C and 85°C - Score=1', 'Temperature of product between 40°C and 85°C'), ('Temperature of product > 85°C - Score=2', 'Temperature of product > 85°C')], default='Temperature of product < 40°C - Score=0', max_length=100, verbose_name='5a: Type of bottom'),
        ),
    ]
