# Generated by Django 3.2 on 2021-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0014_alter_storageconditions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcorrosivity',
            name='name',
            field=models.CharField(choices=[('Slops, corrosive or aggresive chemical, raw water, brine (Unprotected) - Score=2', 'Slops, corrosive or aggresive chemical, raw water, brine (Unprotected)'), ('Slops, corrosive or aggresive chemical, raw water, brine (Internally protected) - Score=1', 'Slops, corrosive or aggresive chemical, raw water, brine (Internally protected)'), ('Fatty acids like Bio-fuels, Palm Oil (Unprotected) - Score=2', 'Fatty acids like Bio-fuels, Palm Oil (Unprotected)'), ('Fatty acids like Bio-fuels, Palm Oil (Internally protected) - Score=1', 'Fatty acids like Bio-fuels, Palm Oil (Internally protected)'), ('Crude Oil (unprotected) - Score=1', 'Crude Oil (unprotected)'), ('Crude Oil (Internally protected) - Score=0', 'Crude Oil (Internally protected)'), ('Gas Oil, Lube Oil, Diesel Oil, Caustic soda, Inert or nonaggressive chemicals, Ethanol, Methanol, air foam liquid, non-heated fuel oil. - Score=0', 'Gas Oil, Lube Oil, Diesel Oil, Caustic soda, Inert or nonaggressive chemicals, Ethanol, Methanol, air foam liquid, non-heated fuel oil.'), ('Jet A1 (fully internally protected) - Score=0', 'Jet A1 (fully internally protected)'), ('Light products, Kerosene, Gasoline, Cracked distillates, treated water (not internally protected) - Score=0', 'Light products, Kerosene, Gasoline, Cracked distillates, treated water (not internally protected)'), ('Heated products like Class D, E and F fuels in accordance with BS 2869 - Score=1', 'Heated products like Class D, E and F fuels in accordance with BS 2869'), ('Sulphur + heated products like Class G and H fuels in accordance with BS 2869 - Score=2', 'Sulphur + heated products like Class G and H fuels in accordance with BS 2869'), ('De-min Water - Score=1', 'De-min Water'), ('De-min Water (Fully protected) - Score=0', 'De-min Water (Fully protected)'), ('Products with unknown corrosion rates - Score=2', 'Products with unknown corrosion rates')], default='Group 1/Risk H - Score=2', max_length=300, verbose_name='6: Product Corrosivity'),
        ),
    ]
