# Generated by Django 3.2 on 2021-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0018_alter_foundationtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightoffoundation',
            name='name',
            field=models.CharField(choices=[('Height of the foundation is adequate to ensure a dry tank bottom - Score=0', 'Height of the foundation is adequate to ensure a dry tank bottom'), ('Height of the foundation is not adequate to ensure a dry tank bottom - Score=2', 'Height of the foundation is not adequate to ensure a dry tank bottom')], default='Tank bottom free from contact with water - Score=0', max_length=100, verbose_name='8: Height of foundation'),
        ),
    ]
