# Generated by Django 3.2 on 2021-05-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0019_alter_heightoffoundation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundationtype',
            options={'verbose_name': 'Foundation Type', 'verbose_name_plural': 'Foundation Type'},
        ),
    ]
