# Generated by Django 3.2 on 2021-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0020_alter_foundationtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetorepair',
            name='name',
            field=models.CharField(choices=[('No internal entry required, limited repair, no limitation on repair time - Score=1', 'No internal entry required, limited repair, no limitation on repair time'), ('Internal entry required, limited repair (<3 months) - Score=2', 'Internal entry required, limited repair (<3 months)'), ('Internal entry required, major repair (3-8 months)- Score=3', 'Internal entry required, major repair (3-8 months)'), ('Internal entry required, major repair (>8 months)- Score=4', 'Internal entry required, major repair (>8 months)')], default='No internal entry required limited repair, no limitation on repair time - Score=1', max_length=100, verbose_name='10a: Time to repair'),
        ),
    ]
