# Generated by Django 3.2 on 2021-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0022_delete_timetorepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeToRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No internal entry required, limited repair, no limitation on repair time - Score=1', 'No internal entry required, limited repair, no limitation on repair time'), ('Internal entry required, limited repair (<3 months) - Score=2', 'Internal entry required, limited repair (<3 months)'), ('Internal entry required, major repair (3-8 months)- Score=3', 'Internal entry required, major repair (3-8 months)'), ('Internal entry required, major repair (>8 months)- Score=4', 'Internal entry required, major repair (>8 months)')], default='No internal entry required limited repair, no limitation on repair time - Score=1', max_length=100, verbose_name='10a: Time to repair')),
            ],
            options={
                'verbose_name': 'Time To Repair',
                'verbose_name_plural': 'Time To Repair',
            },
        ),
    ]
