# Generated by Django 3.2 on 2021-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0023_timetorepair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productflammabilityaspermcsp',
            name='name',
            field=models.CharField(choices=[('Class III(1) and unclassified product - Score=1', 'Class III(1) and unclassified product'), ('Class II(1) product - Score=2', 'Class II(1) product'), ('Class II(2) and Class III(2) product - Score=3', 'Class II(2) and Class III(2) product'), ('Class I product - Score=4', 'Class I product')], default='Class III(1) and unclassified product - Score=1', max_length=100, verbose_name='12b: Product flammability as per MCSP'),
        ),
    ]
