# Generated by Django 3.2 on 2021-05-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0024_alter_productflammabilityaspermcsp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttoxicity',
            name='name',
            field=models.CharField(choices=[('Non-toxic substance- Score=1', 'Non-toxic substance'), ('Toxic substance if in contact with other substances - Score=2', 'Toxic substance if in contact with other substances'), ('Toxic substance - Score=3', 'Toxic substance'), ('Extremely toxic substance - Score=4', 'Extremely toxic substance')], default='Non-toxic substances- Score=1', max_length=100, verbose_name='12c: Product toxicity'),
        ),
    ]
