# Generated by Django 3.2 on 2021-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0025_alter_producttoxicity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankLocatedNearPublicFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No - Score=0', 'No'), ('Yes - Score=1', 'Yes')], default='No - Score=0', max_length=100, verbose_name='12d: Location of tank farm')),
            ],
            options={
                'verbose_name': 'Tank Located Near Public Fence',
                'verbose_name_plural': 'Tank Located Near Public Fence',
            },
        ),
        migrations.AlterField(
            model_name='environmetalhazardtosoilandwater',
            name='name',
            field=models.CharField(choices=[('No or negligle environment effect - Score=1', 'No or negligle environment effect'), ('Environmental nuisance affecting neighbourhood - Score=2', 'Environmental nuisance affecting neighbourhood'), ('Environmental pollution/Extensive restoration required - Score=3', 'Environmental pollution/Extensive restoration required'), ('Severe demage/nuisance/pollution over large area- Score=4', 'Severe demage/nuisance/pollution over large area')], default='Nor or negligle environment effect - Score=1', max_length=100, verbose_name='14a: Environmetal hazard to soil and water as the potential to cause'),
        ),
    ]
