# Generated by Django 3.2 on 2021-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0028_alter_environmetalhazardtosoilandwater_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapouremission',
            name='name',
            field=models.CharField(choices=[('No or negligible harmful (toxic) release - Score=1', 'No or negligible harmful (toxic) release'), ('Small harmful (toxic) release - Score=2', 'Small harmful (toxic) release'), ('Large (>1000m3) harmful (toxic) release - Score=3', 'Large (>1000m3) harmful (toxic) release')], default='No or negligle harmful (toxic) release - Score=1', max_length=100, verbose_name='14b: Vapour emission'),
        ),
    ]
