# Generated by Django 3.2 on 2021-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0029_alter_vapouremission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndtmethodusedforthicknessmeasurements',
            name='name',
            field=models.CharField(choices=[('Floor scan + US - Score=1', 'Floor scan + US'), ('US on gridline system - Score=0.5', 'US on gridline system'), ('Visual + Spot ultrasonic (US) - Score=0)', 'Visual + Spot ultrasonic (US)')], default='Floor scan + US - Score=-0.1', max_length=100, verbose_name='28: NDT method used for thickness measurements'),
        ),
    ]
