# Generated by Django 3.2 on 2021-05-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0030_alter_ndtmethodusedforthicknessmeasurements_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyofinternalinspections',
            name='name',
            field=models.CharField(choices=[('Multiple inspections carried out - Score=1', 'Multiple inspections carried out'), ('One or two inspections carried out - Score=0.5', 'One or two inspections carried out'), ('No or minimal inspection data available - Score=0', 'No or minimal inspection data available')], default='Multiple inspections carried out - Score=0.1', max_length=100, verbose_name='29: Frequency of internal inspections performed during service life'),
        ),
    ]
