# Generated by Django 3.2 on 2021-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0031_alter_frequencyofinternalinspections_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ndt_Method_And_Qualification_Of_Ndt_Operators_In_Place_And_Assessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=0', max_length=100, verbose_name='Ndt Method And Qualification Of Ndt Operators In Place And Assessed')),
            ],
            options={
                'verbose_name': 'NDT Method And Qualification Of NDT Operators In Place And Assessed',
                'verbose_name_plural': 'NDT Method And Qualification Of Ndt Operators In Place And Assessed',
            },
        ),
    ]
