# Generated by Django 3.2 on 2021-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0032_ndt_method_and_qualification_of_ndt_operators_in_place_and_assessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAvailableOfCompletingPdca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=0', max_length=100, verbose_name='Is Evidence Available Of Completing Pdca Cycle On Inspection Activities?')),
            ],
            options={
                'verbose_name': 'Is Evidence Available Of Completing Pdca Cycle On Inspection Activities',
                'verbose_name_plural': 'Is Evidence Available Of Completing Pdca Cycle On Inspection Activities',
            },
        ),
    ]
