# Generated by Django 3.2 on 2021-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0034_auto_20210514_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoesTheOrganisationHaveTheProperQualificationsToDetermineDegradationsSpeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=0', max_length=100, verbose_name='Does the Organisation Have the Proper Qualifications to Determine Degradations Speeds and Assess Inspection Results?')),
            ],
            options={
                'verbose_name': 'Does the Organisation Have the Proper Qualifications to Determine Degradations Speeds and Assess Inspection Results?',
                'verbose_name_plural': 'Does the Organisation Have the Proper Qualifications to Determine Degradations Speeds and Assess Inspection Results?',
            },
        ),
    ]
