# Generated by Django 3.2 on 2021-05-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0035_doestheorganisationhavetheproperqualificationstodeterminedegradationsspeeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreResultsAlwaysDiscussedInAMultidisciplinaryRbiTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=1', max_length=100, verbose_name='Are Results Always Discussed in a Multidisciplinary RBI Team?')),
            ],
            options={
                'verbose_name': 'Are Results Always Discussed in a Multidisciplinary RBI Team?',
                'verbose_name_plural': 'Are Results Always Discussed in a Multidisciplinary RBI Team?',
            },
        ),
    ]
