# Generated by Django 3.2 on 2021-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0036_areresultsalwaysdiscussedinamultidisciplinaryrbiteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aretrainingrequirementsforrbiteammembersconsistentlyused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=1', max_length=100, verbose_name='Are Training Requirements for RBI Team Members Consistently Used?')),
            ],
            options={
                'verbose_name': 'Are Training Requirements for RBI Team Members Consistently Used?',
                'verbose_name_plural': 'Are Training Requirements for RBI Team Members Consistently Used?',
            },
        ),
    ]
