# Generated by Django 3.2 on 2021-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0037_aretrainingrequirementsforrbiteammembersconsistentlyused'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoesTheItemEvaluationHaveSignificantPitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=1', max_length=100, verbose_name='Does the Item Evaluation Have Significant Pitting?')),
            ],
            options={
                'verbose_name': 'Does the Item Evaluation Have Significant Pitting?',
                'verbose_name_plural': 'Does the Item Evaluation Have Significant Pitting?',
            },
        ),
    ]
