# Generated by Django 3.2 on 2021-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0039_alter_doestheitemevaluationhavesignificantpitting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanTheDegradationMechanismBeRegardedAsLinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=1', max_length=100, verbose_name='Can the Degradation Mechanism be Regarded as Linear?')),
            ],
            options={
                'verbose_name': 'Can the Degradation Mechanism be Regarded as Linear?',
                'verbose_name_plural': 'Can the Degradation Mechanism be Regarded as Linear?',
            },
        ),
    ]
