# Generated by Django 3.2 on 2021-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields', '0040_canthedegradationmechanismberegardedaslinear'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTheConstructionSuchThatCorrosionMayBeReducedByTheChosenWeldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yes - Score=1', 'Yes'), ('No - Score=0', 'No')], default='No - Score=1', max_length=100, verbose_name='Is the Construction such that Corrosion may be Reduced by the Chosen Weld Configuration?')),
            ],
            options={
                'verbose_name': 'Is the Construction such that Corrosion may be Reduced by the Chosen Weld Configuration?',
                'verbose_name_plural': 'Is the Construction such that Corrosion may be Reduced by the Chosen Weld Configuration?',
            },
        ),
    ]
