# Generated by Django 3.2 on 2021-05-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottom_plates', '0005_alter_inspectiondata_type_of_interconnecting_bottom_plate_welds_outside_of_annular_section'),
        ('selectfields', '0041_istheconstructionsuchthatcorrosionmaybereducedbythechosenweldconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeOfInterconnectingBottomPlateWelds',
        ),
    ]
