# Generated by Django 3.1.7 on 2021-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell_plates', '0003_auto_20210407_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probabilityfactordata',
            name='product_corrosivity',
            field=models.CharField(choices=[('Group 1/Risk H - score=2', 'Group 1/Risk H'), ('Group 3/Risk M - score=1', 'Group 3/Risk M'), ('Group 4/Risk L - score=0', 'Group 4/Risk L'), ('Group 5/Risk L - score=0', 'Group 5/Risk L'), ('Group 6/Risk M - score=1', 'Group 6/Risk M')], max_length=100, verbose_name='4: product corrosivity'),
        ),
        migrations.AlterField(
            model_name='probabilityfactordata',
            name='vapour_corrosivity',
            field=models.CharField(choices=[('Group 1/Risk H - score=2', 'Group 1/Risk H'), ('Group 3/Risk M - score=1', 'Group 3/Risk M'), ('Group 4/Risk L - score=0', 'Group 4/Risk L'), ('Group 5/Risk L - score=0', 'Group 5/Risk L'), ('Group 6/Risk M - score=1', 'Group 6/Risk M')], max_length=100, verbose_name='5: Vapour Corrosivity'),
        ),
    ]
