# Generated by Django 3.1.7 on 2021-04-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shell_plates', '0005_auto_20210407_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consequencefactordata',
            name='continued_location_of_tank_farm',
        ),
    ]
