# Generated by Django 3.2 on 2021-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell_plates', '0007_auto_20210407_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consequencefactordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inspectiondata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='probabilityfactordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='results',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
