# Generated by Django 3.1.7 on 2021-04-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCoatingAppliedToShellPlates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('External coating applied and quality is sound - score=0', 'External coating applied and quality is sound'), ('External coating applied and quality is poor - score=1', 'External coating applied and quality is poor'), ('External coating not existing - score=2', 'External coating not existing')], default='External coating applied and quality is sound - score=0', max_length=100, verbose_name='External Coating Applied To Shell Plates')),
            ],
        ),
        migrations.CreateModel(
            name='HeatedCoilsInTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No heating coil or no contact between heating coil and shell plates - score=0', 'No heating coil or no contact between heating coil and shell plates'), ('Presence of heating coil in direct contact with shell plates - score=1', 'Presence of heating coil in direct contact with shell plates')], default='No heating coil or no contact between heating coil and shell plates - score=0', max_length=100, verbose_name='Heated coils in tank')),
            ],
        ),
        migrations.CreateModel(
            name='impressedCoatingAppliedToSheelPlates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internal coating applied and quality is sound - score=0', 'Internal coating applied and quality is sound'), ('Internal coating applied and quality is poor - score=1', 'Internal coating applied and quality is poor'), ('Internal coating not existing - score=2', 'Internal coating not existing')], default='Internal coating applied and quality is sound - score=0', max_length=100, verbose_name='1: impressed Coating Applied To Sheel Plates')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCorrosivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Product group 4 - score=2', 'Product group 4'), ('Product group 5 - score=1', 'Product group 5'), ('Product group 3 - score=0', 'Product group 3'), ('Product group 6 - score=0', 'Product group 6'), ('Product group 1 - score=1', 'Product group 1')], default='Product group 4 - score=2', max_length=100, verbose_name='Product corrosivity')),
            ],
        ),
        migrations.CreateModel(
            name='StorageConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Temperature of product < 40°C - score=0', 'Temperature of product < 40°C'), ('40°C Temperature of product < 85°C - score=1', '40°C Temperature of product < 85°C'), ('Temperature of product > 85{DEGREE_SIGN}C - score=2', 'Temperature of product > 85°C')], default='Temperature of product < 40°C - score=0', max_length=100, verbose_name='Storage conditions')),
            ],
        ),
        migrations.CreateModel(
            name='TankShellHasBeenInsulated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CUI is likely to occur - score=2', 'CUI is likely to occur'), ('Tank shell is properly insulated and CUI is unlikely to occur - score=0', 'Tank shell is properly insulated and CUI is unlikely to occur'), ('Tank shell is not insulated, - score=0', 'Tank shell is not insulated,')], default='CUI is likely to occur - score=2', max_length=100, verbose_name='Tank shell has been insulated, and rain water may cause corrosion under insulation (CUI')),
            ],
        ),
        migrations.CreateModel(
            name='VaporCorrosivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vapour group 4 - score=2', 'Vapour group 4'), ('Vapour group 5 - score=1', 'Vapour group 5'), ('Vapour group 3 - score=0', 'Vapour group 3'), ('Vapour group 6 - score=0', 'Vapour group 6'), ('Vapour group 1 - score=1', 'Vapour group 1')], default='Vapour group 4 - score=2', max_length=100, verbose_name='Vapor corrosivity')),
            ],
        ),
    ]
