# Generated by Django 3.1.7 on 2021-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields_shell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcorrosivity',
            name='name',
            field=models.CharField(choices=[('Group 1/Risk H - score=2', 'Group 1/Risk H'), ('Group 3/Risk M - score=1', 'Group 3/Risk M'), ('Group 4/Risk L - score=0', 'Group 4/Risk L'), ('Group 5/Risk L - score=0', 'Group 5/Risk L'), ('Group 6/Risk M - score=1', 'Group 6/Risk M')], default='Product group 4 - score=2', max_length=100, verbose_name='Product corrosivity'),
        ),
        migrations.AlterField(
            model_name='vaporcorrosivity',
            name='name',
            field=models.CharField(choices=[('Group 1/Risk H - score=2', 'Group 1/Risk H'), ('Group 3/Risk M - score=1', 'Group 3/Risk M'), ('Group 4/Risk L - score=0', 'Group 4/Risk L'), ('Group 5/Risk L - score=0', 'Group 5/Risk L'), ('Group 6/Risk M - score=1', 'Group 6/Risk M')], default='Vapour group 4 - score=2', max_length=100, verbose_name='Vapor corrosivity'),
        ),
    ]
