# Generated by Django 3.1.7 on 2021-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectfields_shell', '0002_auto_20210407_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Negligible or less than 5% of capital cost - score=1', 'Negligible or less than 5% of capital cost'), ('5-10% of capital cost - score=2', '5-10% of capital cost'), ('10-50% of capital cost - score=3', '10-50% of capital cost'), ('>50% of capital cost (new tank) - score=4', '>50% of capital cost (new tank)')], default='Negligible or less than 5% of capital cost - score=1', max_length=100, verbose_name='Cost of repair')),
            ],
            options={
                'verbose_name': 'Cost Of Repair',
                'verbose_name_plural': 'Cost Of Repair',
            },
        ),
        migrations.CreateModel(
            name='ProbableMagnitudeOfProductLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No release of product - score=1', 'No release of product'), ('<5% of tank contents - score=2', '<5% of tank contents'), ('>5% of tank contents - score=3', '>5% of tank contents')], default='No release of product - score=1', max_length=100, verbose_name='Probable magnitude of product loss')),
            ],
            options={
                'verbose_name': 'Probable Magnitude Of ProductLoss',
                'verbose_name_plural': 'Probable Magnitude Of Product Loss',
            },
        ),
        migrations.CreateModel(
            name='TimeToRepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('No internal entry required, limited repair - score=1, no limitation on repair time', 'No internal entry required, limited repair, no limitation on repair time'), ('Internal entry required, limited repair (<3 months) - score=2', 'Internal entry required, limited repair (<3 months)'), ('Internal entry required, major repair (3-8 months - score=3)', 'Internal entry required, major repair (3-8 months)'), ('Internal entry required, major repair (>8 months) - score=4', 'Internal entry required, major repair (>8 months)')], default='No internal entry required, limited repair - score=4', max_length=100, verbose_name='Time to repair')),
            ],
            options={
                'verbose_name': 'Time To Repair',
                'verbose_name_plural': 'Time To Repair',
            },
        ),
        migrations.AlterField(
            model_name='storageconditions',
            name='name',
            field=models.CharField(choices=[('Temperature of product < 40°C - score=0', 'Temperature of product < 40°C'), ('40°C Temperature of product < 85°C - score=1', '40°C Temperature of product < 85°C'), ('Temperature of product > 85°C - score=2', 'Temperature of product > 85°C')], default='Temperature of product < 40°C - score=0', max_length=100, verbose_name='Storage conditions'),
        ),
    ]
